### ISSUE TITLE
Upgrade to FluentAssertions v6

### ISSUE THREAD

**Issue by rikrak** [fluentassertions/fluentassertions.mvc#42]
Updating my project to the latest FluentAssertions library causes runtime errors:
System.MissingMethodException: Method not found: 'Void FluentAssertions.Primitives.ReferenceTypeAssertions`2.set_Subject(!0)'.
    at FluentAssertions.Mvc.ActionResultAssertions..ctor(ActionResult subject)
   at FluentAssertions.Mvc.AssertionsExtensions.Should(ActionResult actual)

This is due to v6 having some breaking changes, specifically around how the Assertions base classes are constructed

**Comment by kevinkuszyk** [comment]
@rikrak apologies again with the delay on this.

As you can probably tell, I'm not spending much time in the .net space at the moment.  As you've been the most active contributor here, how would you feel about coming on board as a maintainer?

And on that subject, we're going to need to ship a new version with this in.  Would you mind to open another PR which bumps the version to `0.9.0`.  Once that's in, I'll cut a new release to NuGet.

**Comment by rikrak** [comment]
Maintainer? Yep, can do. Let me know if there are any rules and such

I think the version is already at v0.9.0. I'm going off memory here though.

**Comment by rikrak** [comment]
Yep it's at v0.9.0 already 
https://github.com/fluentassertions/fluentassertions.mvc/blob/d9e67a2495e2fa59871c835ee3954372360337ee/src/SolutionInfo.cs#L9

**Comment by rikrak** [comment]
@kevinkuszyk is there anything else you need before package release?
